### ISSUE TITLE
Admin access

### ISSUE THREAD

**Issue by wanadzmi** [phpreel/phpreel#6]
Hi. How to login as admin? no DB Seed whatsoever

**Comment by reelsoftware** [comment]
It's strange that I have hard-coded the login credentials for admin in the login form and they should show up there. Anyway, here they are:

email: admin@paulbalan.com
password: 123456789

**Comment by wanadzmi** [comment]
i mean after installation on my local server. There is no existing user in DB. So i can only register myself as user. How to register as admin to see the dashboard?

**Comment by reelsoftware** [comment]
Sorry for the misunderstanding, looking into it, it might be a bug. In the meantime, you can go to the users table in the database (using phpMyAdmin or any other database management tool) and change the "roles" field from user to admin or try reinstalling. For me, the installation went smoothly.

**Comment by wanadzmi** [comment]
change the roles to admin fixed the issue. thank you!

**Comment by reelsoftware** [comment]
You are welcome, took a look in the instalation files and everything looks fine, it might have been a issue with your particular installation.
